name: dsi_projeto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/focado_icon.png